language: node_js
node_js:
  - "4.2.1"
sudo: false

notifications:
  email:
    - c1e192a6-70e8-4e1e-a1da-756f20fd50be@yshing.hk
branches:
  only:
    - master
before_script:
  - npm install -g mocha
install:
  - npm install
script:
  - mocha

